name: "Pull Request (Python)"

on:
  push:
#    paths:
#      - 'python/**'
    branches:
      - main
      - master

jobs:
  PR-Python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Run tox
        working-directory: python/src
        run: tox

      - name: SAM build
        working-directory: python/src
        run: |
          pwd
          ls -l
          ./run.sh -b